### ISSUE TITLE
select application designation

### ISSUE THREAD

**Issue by smartin1** [htwg-cloud-application-development/static-code-analytics-application#43]

**Comment by T1m1** [comment]
(1) SCREAm   /  Source Code REpositoriy Analysis
(2) CORA     / COde Repository Analysis
(3) COCOA    / ClOud COde Analysis
(4) SCALY    / Source Code AnaLYsis
(5) SABRinA  / ScalABle Repositories Analysis
(6) CaSCARA / Code SCAlable Repositories Analysis
(7) COpRA     / COde Repositories Analysis
(8) SuCCESS / Static Cloud CodE Scalable analySis
(9) ToSCANA /  sTatic Source Code ANAlysis
(10) SAChSEN /    StAtic Code ScalablE aNalysis
(11) SCAnDAL /    Static Code vAliDator AnaLysis
(12) SeCuRITY /   Static Code ReposITories analYsis
(13) SASCHA / Scalable Analyiesen of repositories and source code  
(15) SIdECAr      StatIc sourcE Code Analysis

**Comment by SteffenGorenflo** [comment]
Klotz
Runit
Analizit
freshify
Neat
Stoffri

**Comment by T1m1** [comment]
15 SIdECAr 
4 SCALY 
5 SABRinA

**Comment by phaldan** [comment]
3, 4, 2

**Comment by morph0815** [comment]
1,5

**Comment by mGrondzi** [comment]
2,3,4

**Comment by floritron** [comment]
7, 2, 4

**Comment by smartin1** [comment]
4,7,2

**Comment by T1m1** [comment]
Congratulations to SCALY! 

Source Code AnaLYsis / SCALabilitY
