### ISSUE TITLE
Error 500 Instance Limit

### ISSUE THREAD

**Issue by morph0815** [htwg-cloud-application-development/static-code-analytics-application#55]
"You have requested more instances (12) than your current instance limit of 10 allows for the specified instance type. Please visit http://aws.amazon.com/contact-us/ec2-request to request an adjustment to this limit. (Service: AmazonEC2; Status Code: 400; Error Code: InstanceLimitExceeded; Request ID: 1c3340b5-336a-4c5d-bd64-1ddb828ad984)"

**Comment by T1m1** [comment]
done
